apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.elasticsearchApplicationName }}
  labels:
    app: {{ .Values.global.elasticsearchApplicationName }}
{{ include "elasticsearch.labels" . | indent 4 }}
spec:
  ports:
  - name: api
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: internal
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: {{ .Values.global.elasticsearchApplicationName }}
  type: ClusterIP
