apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.applicationName }}
  name: {{ .Values.applicationName }}
spec:
  ports:
  - name: api
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: internal
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: {{ .Values.applicationName }}
  type: ClusterIP
